version: "3.5"

services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
    image: postgres:14.3-alpine
  pgadmin:
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    image: dpage/pgadmin4:8.3
