version: '3.8'
services:
  db:
    image: postgres:14.0-alpine
    container_name: smart_stock_db
    env_file: .env
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    env_file: .env
    restart: always
    ports:
      - '${ADMIN_PG_PORT}:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PG_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
